# More information about the configuration file can be found here:
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-config.html
version = 0.1

[default]
[default.global.parameters]
stack_name = "load-shedding-cal-app-rs"

[default.build.parameters]
cached = true
parallel = true
beta_features = true

[default.sync.parameters]
beta_features = true
watch = true

[default.validate.parameters]
lint = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true
s3_prefix = "load-shedding-cal-app-rs"
region = "eu-west-2"
profile = "dev"
image_repositories = []

[default.package.parameters]
resolve_s3 = true

[default.local_start_api.parameters]
warm_containers = "EAGER"

[default.local_start_lambda.parameters]
warm_containers = "EAGER"
