AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Load shedding calendar in ical format

Globals:
  Function:
    Timeout: 5
    MemorySize: 128

Resources:
  LambdaFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: rust-cargolambda # More info about Cargo Lambda: https://github.com/cargo-lambda/cargo-lambda
    Properties:
      FunctionName: LoadSheddingCalendarRs
      CodeUri: ./rust_app
      Handler: bootstrap
      Runtime: provided.al2
      Architectures:
        - arm64
      Events:
        ICal:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /
            Method: GET

  HttpApi:
    Type: AWS::Serverless::HttpApi

Outputs:
  LambdaEndpoint:
    Description: Endpoint for LambdaFunction
    Value:
      Fn::Sub: https://${HttpApi}.execute-api.${AWS::Region}.amazonaws.com
